export const ALL_DIETS = 'ALL_DIETS';
export const CREATE_DIETS = 'CREATE_DIETS';
export const MODIFY_DIETS = 'MODIFY_DIETS';
export const DELETE_DIET = 'DELETE_DIET';
export const DIET_RECIPES_RELATIONS = 'DIET_RECIPES_RELATIONS';
